/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClfyButton: typeof import('./src/components/Button/Clfy/ClfyButton/index.vue')['default']
    ClfyTitle: typeof import('./src/components/Button/Clfy/ClfyTitle/index.vue')['default']
    DeleteButton: typeof import('./src/components/Button/DeleteButton/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchVupBtn: typeof import('./src/components/Button/SwitchVupBtn/index.vue')['default']
    VoiceButton: typeof import('./src/components/Button/VoiceButton/index.vue')['default']
    VoiceButtonLink: typeof import('./src/components/Button/VoiceButtonLink/index.vue')['default']
  }
}
